import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface SendDigestRequest {
  run_id: string;
  recipient_emails?: string[];
  digest_type: 'chief_of_staff' | 'data_strategist' | 'content_strategist';
}

function generateChiefOfStaffHTML(digest: any, runDate: string): string {
  const riskItems = digest.risk_list || [];
  const blockedItems = digest.blocked_list || [];
  const quickWins = digest.quick_wins || [];

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #e5e5e5; padding-bottom: 10px; }
    h2 { color: #444; margin-top: 24px; }
    .card { background: #f9fafb; border-radius: 8px; padding: 16px; margin: 12px 0; border-left: 4px solid #3b82f6; }
    .risk { border-left-color: #ef4444; }
    .blocked { border-left-color: #f59e0b; }
    .quick-win { border-left-color: #22c55e; }
    .label { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
    .value { font-weight: 600; color: #1a1a1a; }
    .action { background: #eff6ff; padding: 8px 12px; border-radius: 4px; margin-top: 8px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; color: #6b7280; font-size: 12px; }
  </style>
</head>
<body>
  <h1>🎯 Daily Chief of Staff Digest</h1>
  <p><strong>Date:</strong> ${runDate}</p>
  
  <p>${digest.digest_text || 'Here is your daily operations summary.'}</p>
  
  ${riskItems.length > 0 ? `
  <h2>🚨 High-Risk Tasks (${riskItems.length})</h2>
  ${riskItems.map((item: any) => `
    <div class="card risk">
      <div class="label">Task</div>
      <div class="value">${item.task_name}</div>
      <div class="label">Project</div>
      <div class="value">${item.project_name}</div>
      <div class="label">Risk Reason</div>
      <div>${item.risk_reason}</div>
      <div class="action">
        <strong>Next Action:</strong> ${item.next_action}
      </div>
    </div>
  `).join('')}
  ` : ''}
  
  ${blockedItems.length > 0 ? `
  <h2>🛑 Blocked Items (${blockedItems.length})</h2>
  ${blockedItems.map((item: any) => `
    <div class="card blocked">
      <div class="label">Task</div>
      <div class="value">${item.task_name}</div>
      <div class="label">Blocker</div>
      <div class="value">${item.blocker_identity}</div>
      <div class="action">
        <strong>To Unblock:</strong> ${item.unblock_ask}
      </div>
    </div>
  `).join('')}
  ` : ''}
  
  ${quickWins.length > 0 ? `
  <h2>⚡ Quick Wins for Today</h2>
  ${quickWins.map((item: any) => `
    <div class="card quick-win">
      <div class="value">${item.task_name}</div>
      <div><strong>Est. Time:</strong> ${item.estimated_time}</div>
      <div><strong>Impact:</strong> ${item.impact}</div>
    </div>
  `).join('')}
  ` : ''}
  
  <div class="footer">
    <p>This digest was generated by Control Tower AI. <a href="#">View in Dashboard</a></p>
    <p>Actions require approval before execution.</p>
  </div>
</body>
</html>
  `;
}

function generateDataStrategistHTML(report: any, runDate: string): string {
  const summary = report.summary || [];
  const actions = report.actions || [];
  const charts = report.charts || [];

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #e5e5e5; padding-bottom: 10px; }
    h2 { color: #444; margin-top: 24px; }
    .summary-item { background: #f0fdf4; border-radius: 8px; padding: 12px 16px; margin: 8px 0; border-left: 4px solid #22c55e; }
    .action-card { background: #f9fafb; border-radius: 8px; padding: 16px; margin: 12px 0; }
    .effort { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .effort-low { background: #dcfce7; color: #166534; }
    .effort-medium { background: #fef3c7; color: #92400e; }
    .effort-high { background: #fee2e2; color: #991b1b; }
    .confidence { color: #6b7280; font-size: 14px; }
    .chart-placeholder { background: #f3f4f6; border-radius: 8px; padding: 24px; text-align: center; margin: 12px 0; }
    .data-warning { background: #fffbeb; border: 1px solid #fbbf24; border-radius: 8px; padding: 12px; margin: 12px 0; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; color: #6b7280; font-size: 12px; }
  </style>
</head>
<body>
  <h1>📊 Data Strategist Report</h1>
  <p><strong>Date:</strong> ${runDate} | <strong>Confidence:</strong> ${report.confidence || 'Medium'}</p>
  
  <h2>Executive Summary</h2>
  ${summary.map((bullet: string) => `
    <div class="summary-item">• ${bullet}</div>
  `).join('')}
  
  ${charts.length > 0 ? `
  <h2>📈 Charts</h2>
  ${charts.map((chart: any) => `
    <div class="chart-placeholder">
      <strong>${chart.title}</strong>
      <p>${chart.caption}</p>
      <p style="color: #6b7280; font-size: 12px;">[View interactive chart in dashboard]</p>
    </div>
  `).join('')}
  ` : ''}
  
  <h2>🎯 Recommended Actions</h2>
  ${actions.map((action: any) => `
    <div class="action-card">
      <div><strong>${action.action}</strong></div>
      <div>Owner: <strong>${action.owner}</strong></div>
      <span class="effort effort-${action.effort}">${action.effort.toUpperCase()}</span>
      <span class="confidence">Confidence: ${Math.round(action.confidence * 100)}%</span>
    </div>
  `).join('')}
  
  ${report.data_warnings && report.data_warnings.length > 0 ? `
  <div class="data-warning">
    <strong>⚠️ Data Notes:</strong>
    <ul>
      ${report.data_warnings.map((w: string) => `<li>${w}</li>`).join('')}
    </ul>
  </div>
  ` : ''}
  
  <div class="footer">
    <p>This report was generated by Control Tower AI. <a href="#">View in Dashboard</a></p>
    <p><strong>Reproduce:</strong> <code>${report.reproduce || 'See dashboard for query'}</code></p>
  </div>
</body>
</html>
  `;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, serviceKey, {
      auth: { persistSession: false },
    });

    // Auth check
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { 
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      });
    }

    const { data: { user } } = await supabase.auth.getUser(authHeader.replace('Bearer ', ''));
    if (!user) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { 
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      });
    }

    const body: SendDigestRequest = await req.json();
    const { run_id, recipient_emails, digest_type } = body;

    if (!run_id) {
      return new Response(JSON.stringify({ error: 'run_id is required' }), { 
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      });
    }

    console.log('[send-agent-digest] Sending digest for run:', run_id);

    // Fetch the run record
    const { data: run, error: runError } = await supabase
      .from('ai_agent_runs')
      .select('id, agent_id, ai_summary, created_at, title, category')
      .eq('id', run_id)
      .single();

    if (runError || !run) {
      return new Response(JSON.stringify({ error: 'Run not found' }), { 
        status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      });
    }

    // Get SendGrid API key
    const sendgridApiKey = Deno.env.get('SENDGRID_API_KEY');
    if (!sendgridApiKey) {
      return new Response(JSON.stringify({ error: 'SendGrid API key not configured' }), { 
        status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      });
    }

    const fromEmail = Deno.env.get('SENDGRID_FROM_EMAIL') || 'noreply@sjinnovation.com';
    const runDate = new Date(run.created_at).toLocaleDateString();

    // Generate HTML based on digest type
    let htmlContent: string;
    let subject: string;

    switch (digest_type) {
      case 'chief_of_staff':
        htmlContent = generateChiefOfStaffHTML(run.ai_summary, runDate);
        subject = `🎯 Daily Digest - ${runDate}`;
        break;
      case 'data_strategist':
        htmlContent = generateDataStrategistHTML(run.ai_summary, runDate);
        subject = `📊 Data Strategist Report - ${runDate}`;
        break;
      default:
        htmlContent = `<p>Agent run completed: ${run.title}</p><pre>${JSON.stringify(run.ai_summary, null, 2)}</pre>`;
        subject = `Control Tower Agent Report - ${runDate}`;
    }

    // Determine recipients
    let recipients = recipient_emails || [];
    if (recipients.length === 0) {
      // Get user's email as default
      const { data: userData } = await supabase
        .from('users')
        .select('email')
        .eq('id', user.id)
        .single();

      if (userData?.email) {
        recipients = [userData.email];
      }
    }

    if (recipients.length === 0) {
      return new Response(JSON.stringify({ error: 'No recipients specified' }), { 
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      });
    }

    // Send via SendGrid
    const sendgridResponse = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${sendgridApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        personalizations: recipients.map(email => ({
          to: [{ email }],
          subject,
        })),
        from: {
          email: fromEmail,
          name: 'Control Tower AI'
        },
        content: [
          { type: 'text/html', value: htmlContent }
        ]
      }),
    });

    if (!sendgridResponse.ok) {
      const errorText = await sendgridResponse.text();
      console.error('[send-agent-digest] SendGrid error:', errorText);
      return new Response(JSON.stringify({ 
        error: 'Failed to send email', 
        details: errorText 
      }), {
        status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    console.log('[send-agent-digest] Email sent to', recipients.length, 'recipients');

    return new Response(JSON.stringify({
      success: true,
      message: 'Digest sent successfully',
      recipients_count: recipients.length,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('[send-agent-digest] Error:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Internal server error' 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
