import { useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Download, Loader2, RefreshCw } from "lucide-react";

import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

import type { Database } from "@/integrations/supabase/types";

const AUTO_REFRESH_INTERVAL = 60_000;

interface CodexSuggestionResponse {
  suggestion: string;
  issueId?: string | null;
  logged?: boolean;
}

type IntegrationLog = Database["public"]["Tables"]["integration_logs"]["Row"];

interface GenerateFixVariables {
  log: IntegrationLog;
  auto?: boolean;
}

const buildJsonPreview = (value: unknown) => {
  if (!value) {
    return "{}";
  }

  try {
    return JSON.stringify(value, null, 2);
  } catch (_error) {
    return String(value);
  }
};

export const SettingsErrorLogs = () => {
  const { toast } = useToast();
  const [selectedFunction, setSelectedFunction] = useState<string | null>(null);
  const [suggestion, setSuggestion] = useState<string | null>(null);
  const [issueId, setIssueId] = useState<string | null>(null);
  const [lastGeneratedAt, setLastGeneratedAt] = useState<string | null>(null);
  const autoGeneratedLogIdRef = useRef<string | null>(null);

  const functionsQuery = useQuery({
    queryKey: ["edge-function-list"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("integration_logs")
        .select("integration_type")
        .order("created_at", { ascending: false })
        .limit(100);

      if (error) throw error;

      const unique = new Set(
        (data ?? [])
          .map((row) => row.integration_type)
          .filter((value): value is string => Boolean(value)),
      );

      return Array.from(unique);
    },
    staleTime: AUTO_REFRESH_INTERVAL,
  });

  useEffect(() => {
    if (!selectedFunction && functionsQuery.data && functionsQuery.data.length > 0) {
      setSelectedFunction(functionsQuery.data[0]);
    }
  }, [functionsQuery.data, selectedFunction]);

  const latestLogQuery = useQuery({
    queryKey: ["edge-function-latest-error", selectedFunction],
    enabled: Boolean(selectedFunction),
    queryFn: async () => {
      if (!selectedFunction) return null;

      const { data, error } = await supabase
        .from("integration_logs")
        .select("*")
        .eq("integration_type", selectedFunction)
        .eq("status", "error")
        .order("created_at", { ascending: false })
        .limit(1);

      if (error) throw error;
      return data?.[0] ?? null;
    },
    refetchInterval: AUTO_REFRESH_INTERVAL,
  });

  const {
    mutate: triggerGenerateFix,
    isPending: isGeneratingFix,
  } = useMutation({
    mutationFn: async ({ log }: GenerateFixVariables) => {
      if (!selectedFunction) {
        throw new Error("Select an edge function to analyze the error");
      }

      const { data, error } = await supabase.functions.invoke<CodexSuggestionResponse>(
        "generate-codex-fix",
        {
          body: {
            functionName: selectedFunction,
            logId: log.id,
            errorMessage: log.error_message,
            stackTrace: (log.response_data as { stack?: string } | null)?.stack ?? null,
            requestPayload: log.request_payload,
            responseData: log.response_data,
            timestamp: log.created_at,
          },
        },
      );

      if (error) throw error;
      if (!data) {
        throw new Error("Codex did not return a suggestion");
      }

      return data;
    },
    onSuccess: (data, variables) => {
      setSuggestion(data.suggestion);
      setIssueId(data.issueId ?? null);
      setLastGeneratedAt(new Date().toISOString());

      autoGeneratedLogIdRef.current = variables.log.id;

      if (!variables.auto) {
        toast({
          title: "Codex suggestion ready",
          description: data.logged
            ? "A fix recommendation has been generated and the error was logged as a bug."
            : "A fix recommendation has been generated. Review logging permissions in Supabase.",
        });
      }
    },
    onError: (mutationError, variables) => {
      if (variables?.log?.id) {
        autoGeneratedLogIdRef.current = variables.log.id;
      }

      const description = mutationError instanceof Error ? mutationError.message : "Unknown error";

      toast({
        title: variables?.auto
          ? "Automatic Codex suggestion failed"
          : "Failed to generate Codex suggestion",
        description,
        variant: "destructive",
      });

      if (variables?.auto) {
        console.error("Automatic Codex suggestion failed", mutationError);
      }
    },
  });

  useEffect(() => {
    if (!selectedFunction) {
      setSuggestion(null);
      setIssueId(null);
      setLastGeneratedAt(null);
      autoGeneratedLogIdRef.current = null;
      return;
    }

    const latestLog = latestLogQuery.data;

    if (!latestLog?.id) {
      setSuggestion(null);
      setIssueId(null);
      setLastGeneratedAt(null);
      autoGeneratedLogIdRef.current = null;
      return;
    }

    if (autoGeneratedLogIdRef.current !== latestLog.id) {
      setSuggestion(null);
      setIssueId(null);
      setLastGeneratedAt(null);
    }

    if (autoGeneratedLogIdRef.current === latestLog.id || isGeneratingFix) {
      return;
    }

    triggerGenerateFix({ log: latestLog, auto: true });
  }, [
    isGeneratingFix,
    latestLogQuery.data,
    selectedFunction,
    triggerGenerateFix,
  ]);

  const handleDownloadSuggestion = () => {
    if (!suggestion || !selectedFunction) return;

    const fileContents = [
      `Edge Function: ${selectedFunction}`,
      lastGeneratedAt ? `Generated: ${new Date(lastGeneratedAt).toLocaleString()}` : null,
      "", // blank line before content
      suggestion,
    ]
      .filter(Boolean)
      .join("\n");

    const blob = new Blob([fileContents], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${selectedFunction}-codex-suggestion.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  const requestPreview = useMemo(() => buildJsonPreview(latestLogQuery.data?.request_payload), [
    latestLogQuery.data?.request_payload,
  ]);

  const responsePreview = useMemo(() => buildJsonPreview(latestLogQuery.data?.response_data), [
    latestLogQuery.data?.response_data,
  ]);

  const renderLogContent = () => {
    if (functionsQuery.isLoading) {
      return <p className="text-sm text-muted-foreground">Loading edge functions…</p>;
    }

    if (functionsQuery.error) {
      return (
        <p className="text-sm text-destructive">
          Unable to load edge function list. Check Supabase permissions and try again.
        </p>
      );
    }

    if (!selectedFunction) {
      return <p className="text-sm text-muted-foreground">Select an edge function to view recent errors.</p>;
    }

    if (latestLogQuery.isLoading) {
      return (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          Fetching the latest error log…
        </div>
      );
    }

    if (latestLogQuery.error) {
      return (
        <p className="text-sm text-destructive">
          Failed to fetch the latest error. Verify the integration_logs table and Supabase RLS policies.
        </p>
      );
    }

    if (!latestLogQuery.data) {
      return <p className="text-sm text-muted-foreground">No recent errors found for this edge function.</p>;
    }

    const log = latestLogQuery.data;

    return (
      <div className="space-y-4">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-lg font-semibold">Latest error</h3>
              <Badge variant="destructive">{log.status}</Badge>
            </div>
            <p className="text-sm text-muted-foreground">
              {new Date(log.created_at).toLocaleString()}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => latestLogQuery.refetch()}
            disabled={latestLogQuery.isFetching}
          >
            <RefreshCw className="mr-2 h-4 w-4" />
            Refresh
          </Button>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <div className="space-y-2">
            <p className="text-sm font-medium text-muted-foreground">Error message</p>
            <p className="rounded-md border bg-muted/40 p-3 text-sm">
              {log.error_message || "No error message returned from Supabase."}
            </p>
          </div>

          <div className="space-y-2">
            <p className="text-sm font-medium text-muted-foreground">Performed by</p>
            <p className="rounded-md border bg-muted/40 p-3 text-sm">
              {log.performed_by || "Unknown"}
            </p>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <div className="space-y-2">
            <p className="text-sm font-medium text-muted-foreground">Request payload</p>
            <ScrollArea className="h-48 rounded-md border bg-muted/40 p-3">
              <pre className="whitespace-pre-wrap text-xs">{requestPreview}</pre>
            </ScrollArea>
          </div>
          <div className="space-y-2">
            <p className="text-sm font-medium text-muted-foreground">Response data</p>
            <ScrollArea className="h-48 rounded-md border bg-muted/40 p-3">
              <pre className="whitespace-pre-wrap text-xs">{responsePreview}</pre>
            </ScrollArea>
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium text-muted-foreground">Codex suggested fix</p>
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={() => triggerGenerateFix({ log, auto: false })}
                disabled={isGeneratingFix}
              >
                {isGeneratingFix ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <RefreshCw className="mr-2 h-4 w-4" />
                )}
                Regenerate
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={handleDownloadSuggestion}
                disabled={!suggestion}
              >
                <Download className="mr-2 h-4 w-4" />
                Download fix
              </Button>
            </div>
          </div>
          <Textarea
            value={suggestion ?? ""}
            readOnly
            placeholder="Codex recommendations will appear here once generated."
            className="min-h-[180px]"
          />
          {lastGeneratedAt && (
            <p className="text-xs text-muted-foreground">
              Last generated {new Date(lastGeneratedAt).toLocaleString()}
            </p>
          )}
          {issueId && (
            <p className="text-xs text-muted-foreground">
              Logged as bug ID <span className="font-medium">{issueId}</span> in the issues table.
            </p>
          )}
        </div>
      </div>
    );
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Error Logs</CardTitle>
        <CardDescription>
          Review the most recent Supabase Edge Function failures, let Codex suggest fixes, and export guidance for your
          engineering team.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <p className="text-sm font-medium">Edge function</p>
          <Select
            value={selectedFunction ?? undefined}
            onValueChange={(value) => {
              setSelectedFunction(value);
              setSuggestion(null);
              setIssueId(null);
              setLastGeneratedAt(null);
              autoGeneratedLogIdRef.current = null;
            }}
            disabled={functionsQuery.isLoading || !functionsQuery.data?.length}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select edge function" />
            </SelectTrigger>
            <SelectContent>
              {(functionsQuery.data ?? []).map((fn) => (
                <SelectItem value={fn} key={fn}>
                  {fn}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {!functionsQuery.isLoading && (functionsQuery.data?.length ?? 0) === 0 && (
            <p className="text-xs text-muted-foreground">
              No edge function activity recorded. Trigger an edge function to populate the logs table.
            </p>
          )}
        </div>

        <div>{renderLogContent()}</div>
      </CardContent>
    </Card>
  );
};

export default SettingsErrorLogs;
